source: site
paths:
  uploads: uploads
  static: ''
collections_config:
  data:
    path: _data
    disable_url: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  posts:
    path: collections/_posts
    url: /blog/[full_slug]/
    create:
      path: >-
        [relative_base_path]/{date|year}-{date|month}-{date|day}-{title|slugify}.[ext]
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: site/schemas/post.md
  pages:
    path: collections/_pages
    url: "/[full_slug]/"
    icon: wysiwyg
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: site/schemas/page.html
  projects:
    path: collections/_projects
    url: "/projects/[full_slug]/"
    description: ''
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: site/schemas/project.md
  testimonials:
    path: collections/_testimonials
    disable_url: true
    description: ''
    icon: format_quote
    sort:
      key: name
    sort_options:
      - key: name
      - key: name
        order: desc
      - key: position
      - key: position
        order: desc
    _enabled_editors:
      - data
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: site/schemas/testimonial.md
  drafts:
    path: collections/_drafts
    url: "/blog/[full_slug]/"
    create:
      publish_to: posts
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
collection_groups:
  - heading: Content
    collections:
      - pages
      - projects
      - testimonials
  - heading: Blogging
    collections:
      - posts
      - drafts
  - heading: Settings
    collections:
      - data
_inputs:
  tags:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
_structures:
  content_blocks:
    style: modal
data_config: true
timezone: Etc/UTC
